version: "3.7"
services:

  frontend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    image: frontend:0.1
    restart: always
    ports:
      - "33000:80"
    networks:
      - springapimysql-net
    depends_on:
      - backend


  backend:
    platform: linux/x86_64  
    build: .
    container_name: backend
    image: backend:0.1
    restart: always
    ports:
      - "33500:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/test?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
    
      
  mysqldb:
    platform: linux/x86_64  
    image: mysql:8.0
    container_name: database
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net  
    environment:
      MYSQL_USER: yash
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: yash
      MYSQL_ROOT_PASSWORD: yash
    volumes:
      - ./mysql_data:/var/lib/mysql
       
      
networks:
  springapimysql-net:
    driver: bridge